# Generated by Django 5.1.4 on 2025-03-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_rename_address_employee_eaddr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyEmployee',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('firstapp.employee',),
        ),
    ]
